//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject.Models
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Class PublicToilet.
    /// </summary>
    public partial class PublicToilet
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>The identifier.</value>
        public int Id { get; set; }
        /// <summary>
        /// Gets or sets the lat.
        /// </summary>
        /// <value>The lat.</value>
        public Nullable<decimal> lat { get; set; }
        /// <summary>
        /// Gets or sets the lon.
        /// </summary>
        /// <value>The lon.</value>
        public Nullable<decimal> lon { get; set; }
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>The name.</value>
        public string name { get; set; }
        /// <summary>
        /// Gets or sets the female.
        /// </summary>
        /// <value>The female.</value>
        public string female { get; set; }
        /// <summary>
        /// Gets or sets the male.
        /// </summary>
        /// <value>The male.</value>
        public string male { get; set; }
        /// <summary>
        /// Gets or sets the wheelchair.
        /// </summary>
        /// <value>The wheelchair.</value>
        public string wheelchair { get; set; }
        /// <summary>
        /// Gets or sets the operator.
        /// </summary>
        /// <value>The operator.</value>
        public string @operator { get; set; }
        /// <summary>
        /// Gets or sets the baby facil.
        /// </summary>
        /// <value>The baby facil.</value>
        public string baby_facil { get; set; }
        /// <summary>
        /// Gets or sets the location.
        /// </summary>
        /// <value>The location.</value>
        public string location { get; set; }
    }
}
